#!/usr/bin/env node
// Builds figma-levels.svg — the shipped levels, laid out side by side as
// one artboard each, in the same vocabulary as the design pack. Paste it into
// Figma and you can edit real levels immediately instead of starting from a
// blank page; it also doubles as the worked example of the naming convention.
//
//   node levels-to-svg.mjs            # all levels
//   node levels-to-svg.mjs 1 2 9      # just these
//
// Round trip: this is the *out* direction. The *in* direction reads the same
// names back off a Figma selection — see README.md.

import { writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { LEVELS } from "../lib.mjs";
import { newDoc, slug, S, BG, GUIDE, INK } from "./svgkit.mjs";

const picked = process.argv.slice(2).map(Number).filter((n) => Number.isInteger(n));
const idxs = picked.length ? picked : LEVELS.map((_, i) => i);

const GAP = 120; // px between artboards
const PAD = 40;  // px of margin inside one, past the level's own bounds

const d = newDoc();
let cursorX = PAD;
let sheetH = 0;

for (const li of idxs) {
  const L = LEVELS[li];
  if (!L) continue;
  // initLevel already computed padded world bounds; use them as the artboard.
  const b = L.bounds;
  const w = (b.x1 - b.x0) * S + PAD * 2;
  const h = (b.y1 - b.y0) * S + PAD * 2;
  const ox = cursorX + PAD - b.x0 * S; // px of world x=0 inside this artboard
  const oy = 60 + PAD - b.y0 * S;

  // The artboard. A pasted <rect> arrives as a rect, not a Frame — select it
  // plus its contents and hit ⌘⌥G ("Frame selection") to promote it, or let
  // the plugin/MCP path build real Frames in the first place.
  // The frame name is the whole contract: "L--" plus the level's own title
  // (which already carries its number). The reader turns the hyphens back into
  // spaces, so a round trip keeps the name it shipped with.
  d.rect("frame", cursorX, 60, w, h,
         { id: "L--" + slug(L.name), fill: BG, stroke: GUIDE, dash: "12 10" });
  d.label(cursorX, 44, L.name, { size: 15, weight: 700, fill: INK });

  for (const p of L.terrain) d.poly(ox, oy, p);
  for (const c of L.cushions) d.cushion(ox + c.x * S, oy + c.y * S, c.w);
  for (const pp of L.pops) d.popper(ox + pp.x * S, oy + pp.y * S, pp.spd, pp.deg);
  for (const bp of L.bumpers) d.bumper(ox + bp.x * S, oy + bp.y * S);
  for (const m of L.cans) d.can(ox + m[0] * S, oy + m[1] * S);
  d.start(ox + L.start[0] * S, oy + L.start[1] * S);
  d.goal(ox + L.goal[0] * S, oy + L.goal[1] * S);

  // No bands. A frame used to carry the level's baked solution as dashed
  // `band` layers, and the readers turned them back into `solution` — an answer
  // key drawn by hand, stale the moment the geometry moved beneath it. The
  // frame is the GEOMETRY now; what solves it is `verify.mjs`'s to find.

  d.label(cursorX, 60 + h + 22,
          L.cans.length + " cans" +
          (L.pops.length ? " · " + L.pops.length + " poppers" : "") +
          (L.bumpers.length ? " · " + L.bumpers.length + " bumpers" : ""),
          { size: 11 });

  cursorX += w + GAP;
  sheetH = Math.max(sheetH, 60 + h + 60);
}

const here = dirname(fileURLToPath(import.meta.url));
await writeFile(
  join(here, "figma-levels.svg"),
  d.render(Math.round(cursorX + PAD), Math.round(sheetH),
           "Goomba Glider levels " + idxs.map((i) => i + 1).join(",") +
           " — generated by tools/goomba/figma/levels-to-svg.mjs"),
);
console.log("figma-levels.svg  " + idxs.length + " artboards  " +
            Math.round(cursorX + PAD) + "x" + Math.round(sheetH) + "px  " +
            d.count() + " nodes");
