#!/usr/bin/env node
// Builds figma-levels.svg — a PACK, one artboard per level, in the design
// pack's vocabulary. A TRACING TEMPLATE: Figma's SVG import keeps the NAME off
// the `id` but flattens every shape to a VECTOR, which the reader refuses for
// `t`, so a level pasted from here does not read back until its terrain is
// redrawn as Lines and its toys swapped for kit instances. For a round trip
// use `kiwi.mjs` (`draft.mjs figma --kiwi`).
//
// Point it at a pack: --pack <file>, GOOMBA_PACK=<file>, or tools/goomba/
// pack.json (gitignored). The output is gitignored too.
//
//   node levels-to-svg.mjs            # all levels
//   node levels-to-svg.mjs 1 2 9      # just these

import { writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { allIndexes, levelAt } from "../lib.mjs";
import { newDoc, slug, S, BG, GUIDE, INK } from "./svgkit.mjs";

const picked = process.argv.slice(2).map(Number).filter((n) => Number.isInteger(n));
const idxs = picked.length ? picked : allIndexes();

const GAP = 120; // px between artboards
const PAD = 40;  // px of margin inside one, past the level's own bounds

const d = newDoc();
let cursorX = PAD;
let sheetH = 0;

for (const li of idxs) {
  const L = levelAt(li);
  // The artboard IS the level's world. A `frame` is AUTHORED (its empty space
  // is a design decision) and is used verbatim, so export -> paste -> export
  // is a fixed point rather than a world that grows by PAD every pass.
  const b = L.frame ?? {
    x0: L.bounds.x0 - PAD / S, y0: L.bounds.y0 - PAD / S,
    x1: L.bounds.x1 + PAD / S, y1: L.bounds.y1 + PAD / S,
  };
  const w = (b.x1 - b.x0) * S;
  const h = (b.y1 - b.y0) * S;
  const ox = cursorX - b.x0 * S; // px of world x=0 inside this artboard
  const oy = 60 - b.y0 * S;

  // A pasted <rect> arrives as a rect, not a Frame (⌘⌥G promotes it). The id
  // is the whole contract: "L--" plus the title and NO number (`levelLabel`
  // numbers from pack position); the reader turns the hyphens back into spaces.
  // The caption is a Text layer every reader ignores.
  d.rect("frame", cursorX, 60, w, h,
         { id: "L--" + slug(L.name), fill: BG, stroke: GUIDE, dash: "12 10" });
  d.label(cursorX, 44, `${li + 1} · ${L.name}`, { size: 15, weight: 700, fill: INK });

  for (const p of L.terrain) d.poly(ox, oy, p);
  for (const c of L.cushions) d.cushion(ox + c.x * S, oy + c.y * S, c.w);
  for (const pp of L.pops) d.popper(ox + pp.x * S, oy + pp.y * S, pp.spd, pp.deg);
  for (const bp of L.bumpers) d.bumper(ox + bp.x * S, oy + bp.y * S);
  for (const m of L.cans) d.can(ox + m[0] * S, oy + m[1] * S);
  d.start(ox + L.start[0] * S, oy + L.start[1] * S);
  d.goal(ox + L.goal[0] * S, oy + L.goal[1] * S);

  // No bands: a frame is the GEOMETRY, and the readers ignore `band` layers.

  d.label(cursorX, 60 + h + 22,
          L.cans.length + " cans" +
          (L.pops.length ? " · " + L.pops.length + " poppers" : "") +
          (L.bumpers.length ? " · " + L.bumpers.length + " bumpers" : ""),
          { size: 11 });

  cursorX += w + GAP;
  sheetH = Math.max(sheetH, 60 + h + 60);
}

const here = dirname(fileURLToPath(import.meta.url));
await writeFile(
  join(here, "figma-levels.svg"),
  d.render(Math.round(cursorX + PAD), Math.round(sheetH),
           "Goomba Glider levels " + idxs.map((i) => i + 1).join(",") +
           " — generated by tools/goomba/figma/levels-to-svg.mjs"),
);
console.log("figma-levels.svg  " + idxs.length + " artboards  " +
            Math.round(cursorX + PAD) + "x" + Math.round(sheetH) + "px  " +
            d.count() + " nodes");
